name: Get GitHub Stats

on:
  schedule:
    - cron: '* * * * *' # Ejecutar cada minuto

jobs:
  get-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm install node-fetch
         
      - name: Run Node.js script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node index.js
