name: Update Readme

on:
  schedule:
    - cron: '*/2 * * * *'  # Ejecutar cada 2 minutos
  workflow_dispatch:

jobs:
  get-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  # Utiliza la versión de Node.js adecuada
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
      
      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run Node.js script
        env:
          GH_TOKEN: ${{ secrets.GH_APIKEY_2 }}
          USERNAME: ${{ github.repository_owner }}
        run: node index.js

      - name: Check for changes & Git commit - Git Push/Pull
        run: |
          git diff --exit-code || (git add -A . && git commit -m "Updated" && git pull origin main && git push origin main)
