name: Run Update Stats GH Actions (Features)

on:
  push:
    branches:
      - features/modularization-of-methods
  workflow_dispatch:

jobs:
  get-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1        
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
            filename:  images/metrics.base.svg
            token: ${{ secrets.GITH_TOKEN }}
            base: header, activity, community, repositories, metadata 
            
      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename:  images/metrics.plugin.activity.svg
          token: ${{ secrets.GITH_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
         
      - name: Terminal Generator
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename:  images/metrics.terminal.svg
          token: ${{ secrets.GITH_TOKEN }}
          base: header, metadata
          
      - name:  Language stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITH_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: firstname lastname, username, username@users.noreply.github.com
          
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics.plugin.habits.charts.svg
          token: ${{ secrets.GITH_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: America/Bogota
            
      
      - name: Configure Git
        run: |
          git config user.name "Libardo Lozano (Bot)"
          git config user.email "lilozanoga@unal.edu.co"
          
      - name: Switch to the desired branch
        run: git checkout features/modularization-of-methods

      - name: Fetch latest changes
        run: git fetch origin main
      
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  
      
      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run Node.js script
        env:
          GH_TOKEN: ${{ secrets.GH_APIKEY_2 }}
        run: node index.js

      - name: Check for changes
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "No changes to commit"
            exit 0
          fi
      

      - name: Git commit - Git Push/Pull
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No hay cambios para agregar"
          else
            git add -A .
            git commit -m "Readme and Schemas are updated"
            git fetch origin features/modularization-of-methods
            git pull origin features/modularization-of-methods
            git push origin features/modularization-of-methods
          fi
        
        
