name: Run Update Stats GH Actions
on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:

jobs:
  get-stats:
    runs-on: ubuntu-latest

    steps:

      
    
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v3

      - name:  Generate 3D Contrib stats Grid
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name:  Generate Snake Contribution grid 
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake-contrib/github-snake.svg
            snake-contrib/github-snake-dark.svg?palette=github-dark
            snake-contrib/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
      - name: Configure Git
        run: |
          git config user.name "Libardo Lozano (Bot)"
          git config user.email "lilozanoga@unal.edu.co"
          
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  
      
      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run Node.js script
        env:
          GH_TOKEN: ${{ secrets.GH_APIKEY_2 }}
        run: node index.js

      - name: Check for changes
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "No changes to commit"
            exit 0
          fi
      

      - name: Git commit - Git Push/Pull
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No hay cambios para agregar"
          else
            git add -A .
            git commit -m "Readme and Schemas are updated"
            git pull origin main
            git push origin main  # Asegúrate de especificar la rama correcta
          fi
