name: Run GH Actions & GH Stats

on:
  schedule:
    - cron: '0 */2 * * *'  # Ejecutar cada 2 horas
  workflow_dispatch:

jobs:
  get-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  
      
      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run Node.js script
        env:
          GH_TOKEN: ${{ secrets.GH_APIKEY_2 }}
        run: node index.js

      - name: Check for changes
        run: |
          if [[ -z $(git status -s) ]]; then
            echo "No changes to commit"
            exit 0
          fi
      
      - name: Git commit - Git Push/Pull
        run: |
          git add -A .
          git commit -m "Updated"
          git pull origin main
          git push origin main  # Asegúrate de especificar la rama correcta
